-- =====================================================================
-- TechMart Online - sample / seed data
-- Login credentials (salted SHA-256 hashes generated by PasswordUtil):
--   ADMIN     : admin    / admin123
--   CUSTOMER  : customer / password123
--   DEVELOPER : devuser  / dev123
-- Run after schema.sql:  mysql -u root -p techmart < sample-data.sql
-- =====================================================================
USE techmart;

-- ---- Users -----------------------------------------------------------
INSERT INTO users (username, email, password_hash, salt, first_name, last_name, phone, role, active, created_at) VALUES
('admin',    'admin@techmart.lk',    '09t2rtymWHytfAaWzgDMJ3gZ6hV46K8OU4Vj9R7nGmY=', '565Gb5bl/P0eV1o2eYD2Ow==', 'System',  'Administrator', '+94112000001', 'ADMIN',     TRUE, NOW()),
('customer', 'customer@techmart.lk', 'kMMtXaXxkWz4bGxD+tA1C7/RTxr8HVP9x9WhcxDOUEs=', 'g5ld+ZeDOYlqzMYsUecd1Q==', 'Nimal',   'Perera',        '+94112000002', 'CUSTOMER',  TRUE, NOW()),
('devuser',  'dev@techmart.lk',      'z40QVRLwA1UC8M3ryBDi2nGuEtOjpBeeM5pE4cGcmM0=', 'nNMqSk8qBKS4/zmb+rs51A==', 'Dev',     'Engineer',      '+94112000003', 'DEVELOPER', TRUE, NOW());

-- ---- Categories ------------------------------------------------------
INSERT INTO categories (id, name, description, image_url, parent_id) VALUES
(1, 'Electronics',  'All electronic devices',            'https://picsum.photos/seed/tmcat1/400/300', NULL),
(2, 'Smartphones',  'Latest flagship and mid-range phones','https://picsum.photos/seed/tmcat2/400/300', 1),
(3, 'Laptops',      'Ultrabooks, gaming and business laptops','https://picsum.photos/seed/tmcat3/400/300', 1),
(4, 'Audio',        'Headphones, earbuds and speakers',  'https://picsum.photos/seed/tmcat4/400/300', 1),
(5, 'Accessories',  'Chargers, storage and peripherals', 'https://picsum.photos/seed/tmcat5/400/300', 1);

-- ---- Warehouses ------------------------------------------------------
INSERT INTO warehouses (id, name, location, address, active) VALUES
(1, 'Colombo DC', 'Colombo',  'No. 1 Industrial Estate, Colombo 15', TRUE),
(2, 'Kandy DC',   'Kandy',    'No. 22 Peradeniya Road, Kandy',       TRUE),
(3, 'Galle DC',   'Galle',    'No. 8 Matara Road, Galle',            TRUE);

-- ---- Products (20) ---------------------------------------------------
INSERT INTO products (id, name, description, sku, price, discounted_price, brand, image_url, active, version, created_at) VALUES
(1,  'Samsung Galaxy S24 Ultra', '6.8" QHD+ AMOLED, Snapdragon 8 Gen 3, 200MP camera, S-Pen', 'SM-SGS24U', 490.00, 470.00, 'Samsung', 'https://picsum.photos/seed/tm1/400/300', TRUE, 0, NOW()),
(2,  'Apple iPhone 15 Pro',      'A17 Pro chip, titanium frame, 48MP main camera',           'SM-IP15P',  499.00, NULL,      'Apple',   'https://picsum.photos/seed/tm2/400/300', TRUE, 0, NOW()),
(3,  'Google Pixel 8 Pro',       'Tensor G3, 50MP triple camera, 7 years of updates',        'SM-PIX8P',  480.00, NULL,      'Google',  'https://picsum.photos/seed/tm3/400/300', TRUE, 0, NOW()),
(4,  'Xiaomi 14',                'Leica optics, Snapdragon 8 Gen 3, 120Hz LTPO',             'SM-XM14',   450.00, NULL,      'Xiaomi',  'https://picsum.photos/seed/tm4/400/300', TRUE, 0, NOW()),
(5,  'OnePlus 12',               'Snapdragon 8 Gen 3, 100W charging, Hasselblad camera',     'SM-OP12',   460.00, 440.00, 'OnePlus', 'https://picsum.photos/seed/tm5/400/300', TRUE, 0, NOW()),
(6,  'MacBook Pro 14 M3',        'M3 Pro, 18GB RAM, 512GB SSD, Liquid Retina XDR',           'LT-MBP14',  499.00, 489.00, 'Apple',   'https://picsum.photos/seed/tm6/400/300', TRUE, 0, NOW()),
(7,  'Dell XPS 15',              '13th Gen i7, RTX 4050, 16GB, 1TB, 3.5K OLED',              'LT-XPS15',  495.00, NULL,      'Dell',    'https://picsum.photos/seed/tm7/400/300', TRUE, 0, NOW()),
(8,  'Lenovo ThinkPad X1 Carbon','14" 2.8K OLED, i7, 32GB, business ultrabook',             'LT-TPX1',   492.00, NULL,      'Lenovo',  'https://picsum.photos/seed/tm8/400/300', TRUE, 0, NOW()),
(9,  'Asus ROG Zephyrus G16',    'i9, RTX 4070, 240Hz OLED gaming laptop',                   'LT-ROGZ',   498.00, 488.00, 'Asus',    'https://picsum.photos/seed/tm9/400/300', TRUE, 0, NOW()),
(10, 'HP Spectre x360',          '2-in-1 convertible, i7, 16GB, 1TB, OLED touch',            'LT-SPECX',  493.00, NULL,      'HP',      'https://picsum.photos/seed/tm10/400/300', TRUE, 0, NOW()),
(11, 'Sony WH-1000XM5',          'Industry-leading noise cancelling over-ear headphones',    'AU-SXM5',   350.00, 320.00,  'Sony',      'https://picsum.photos/seed/tm11/400/300', TRUE, 0, NOW()),
(12, 'Apple AirPods Pro 2',      'Active noise cancellation, USB-C, adaptive audio',         'AU-APP2',   299.00,  NULL,      'Apple',     'https://picsum.photos/seed/tm12/400/300', TRUE, 0, NOW()),
(13, 'Bose QuietComfort Ultra',  'Immersive audio, world-class noise cancelling',            'AU-BQCU',   380.00, NULL,      'Bose',      'https://picsum.photos/seed/tm13/400/300', TRUE, 0, NOW()),
(14, 'Sennheiser Momentum 4',    '60h battery, audiophile sound, adaptive ANC',              'AU-SNM4',   340.00,  NULL,      'Sennheiser','https://picsum.photos/seed/tm14/400/300', TRUE, 0, NOW()),
(15, 'JBL Charge 5',             'Portable waterproof Bluetooth speaker, powerbank',         'AU-JBLC5',  199.00,  179.00,  'JBL',       'https://picsum.photos/seed/tm15/400/300', TRUE, 0, NOW()),
(16, 'Anker 65W GaN Charger',    'Compact 3-port USB-C fast charger',                        'AC-ANK65',  99.00,   NULL,      'Anker',    'https://picsum.photos/seed/tm16/400/300', TRUE, 0, NOW()),
(17, 'Logitech MX Master 3S',    'Ergonomic wireless mouse, 8K DPI, quiet clicks',           'AC-MXM3S',  150.00,  130.00,  'Logitech', 'https://picsum.photos/seed/tm17/400/300', TRUE, 0, NOW()),
(18, 'Samsung 1TB T7 SSD',       'Portable USB 3.2 SSD, 1050MB/s',                           'AC-SS1TB',  199.00,  NULL,      'Samsung',  'https://picsum.photos/seed/tm18/400/300', TRUE, 0, NOW()),
(19, 'Spigen Tough Armor Case',  'Rugged protective phone case',                             'AC-SPGN',   49.00,   NULL,      'Spigen',   'https://picsum.photos/seed/tm19/400/300', TRUE, 0, NOW()),
(20, 'UGREEN USB-C Hub 9-in-1',  'HDMI, USB-A, SD, PD passthrough docking hub',              'AC-UGHUB',  120.00,  NULL,      'UGREEN',   'https://picsum.photos/seed/tm20/400/300', TRUE, 0, NOW());

-- ---- Inventory (every product in every warehouse; product 20 is OUT OF STOCK to demo back-in-stock) ----
INSERT INTO inventory (product_id, warehouse_id, quantity_available, quantity_reserved, reorder_threshold, reorder_quantity, last_updated)
SELECT p.id, w.id,
       CASE WHEN p.id = 20 THEN 0
            WHEN p.id IN (9, 13) THEN 5            -- intentionally low stock to show alerts
            ELSE 20 + (p.id * 2) + (w.id * 4)
       END,
       0, 10, 50, NOW()
FROM products p CROSS JOIN warehouses w;

-- ---- Sample order 1: DELIVERED + COMPLETED payment ------------------
INSERT INTO orders (order_number, user_id, status, subtotal, tax, shipping_cost, total_amount, shipping_address, order_date, processed_at, shipped_at, delivered_at)
SELECT 'TM-SAMPLE-0001', u.id, 'DELIVERED', 369990.00, 29599.20, 350.00, 399939.20,
       '123 Galle Road, Colombo 03', NOW() - INTERVAL 5 DAY, NOW() - INTERVAL 5 DAY, NOW() - INTERVAL 4 DAY, NOW() - INTERVAL 2 DAY
FROM users u WHERE u.username = 'customer';

INSERT INTO order_items (order_id, product_id, quantity, unit_price, total_price, product_snapshot_name, product_snapshot_sku)
SELECT o.id, p.id, 1, 369990.00, 369990.00, p.name, p.sku
FROM orders o JOIN products p ON p.sku = 'SM-SGS24U'
WHERE o.order_number = 'TM-SAMPLE-0001';

INSERT INTO payments (order_id, payment_reference, gateway_transaction_id, status, amount, currency, payment_method, initiated_at, completed_at)
SELECT o.id, 'PAY-SAMPLE-0001', 'PH-SAMPLE-1', 'COMPLETED', 399939.20, 'LKR', 'VISA', NOW() - INTERVAL 5 DAY, NOW() - INTERVAL 5 DAY
FROM orders o WHERE o.order_number = 'TM-SAMPLE-0001';

-- ---- Sample order 2: PENDING (awaiting payment) ---------------------
INSERT INTO orders (order_number, user_id, status, subtotal, tax, shipping_cost, total_amount, shipping_address, order_date)
SELECT 'TM-SAMPLE-0002', u.id, 'PENDING', 599980.00, 47998.40, 350.00, 648328.40,
       '45 Peradeniya Road, Kandy', NOW() - INTERVAL 1 DAY
FROM users u WHERE u.username = 'customer';

INSERT INTO order_items (order_id, product_id, quantity, unit_price, total_price, product_snapshot_name, product_snapshot_sku)
SELECT o.id, p.id, 2, 299990.00, 599980.00, p.name, p.sku
FROM orders o JOIN products p ON p.sku = 'SM-PIX8P'
WHERE o.order_number = 'TM-SAMPLE-0002';

-- ---- A back-in-stock subscription for the out-of-stock product ------
INSERT INTO stock_alerts (user_id, product_id, notified, created_at)
SELECT u.id, p.id, FALSE, NOW()
FROM users u CROSS JOIN products p
WHERE u.username = 'customer' AND p.sku = 'AC-UGHUB';
